/* =====================================================================
   config.js -- ALL THE NUMBERS.
   Change the values in the ENEMIES section to tune enemy difficulty.
   ===================================================================== */
var CONFIG = {
  TILE: 40,
  ROWS: 10,
  PIECE_COLS: 8,
  CANVAS_W: 800,
  CANVAS_H: 400,

  MOVE_SPEED: 0.2,
  JUMP_POWER: 12,
  GRAVITY: 0.5,
  MAX_FALL: 16,
  MAX_HORIZONTAL_SPEED: 7.5,
  MAX_VERTICAL_SPEED: 16,
  PLAYER_SIZE: 32,
  PLAYER_RADIUS: 16,

  WEAPON_PROJECTILE_SPEED: 12,
  WEAPON_RELOAD_FRAMES: { bazooka: 360, ak47: 270, pistols: 180 },
  BAZOOKA_FIRE_COOLDOWN: 120,
  CLASS_STATS: {
    bazooka: { damage: 85, ammo: 3 },
    ak47: { damage: 7, ammo: 20 },
    pistols: { damage: 4, ammo: 24 }
  },
  BAZOOKA_BLAST_RADIUS: 58,
  BAZOOKA_KNOCKBACK: 14,
  BAZOOKA_EXPLOSION_TIME: 18,
  AK_THROW_SPEED: 13,
  AK_THROW_DAMAGE: 25,
  AK_RETURN_TIME: 42,
  PISTOL_DASH_SPEED: 10,
  PISTOL_DASH_TIME: 14,
  PISTOL_DASH_COOLDOWN: 45,

  LINE_WIDTH: 3,
  DOT_DISTANCE: 0.55,

  // --- adjustable enemy variables --------------------------------------
  ENEMY_START_DISTANCE: 280,
  ENEMY_RESPAWN_DISTANCE: 520,
  ENEMY_WINDUP_FRAMES: 60,
  ENEMY_SPAWN_HEIGHT: 100,
  CUOBID_SPEED: 1.05,
  CUOBID_DISTANCE_SPEED: 0.0025,
  CUOBID_MAX_SPEED: 8,
  CUOBID_GROUP_SIZE: 2,
  CUOBID_SIZE: 48,
  CUOBID_SPAWN_SPACING: 500,
  CUOBID_MERGE_DISTANCE: 72,
  CUOBID_HIT_KNOCKBACK: 12,
  DRONE_FOLLOW_RATE: 0.02,
  DRONE_FAST_FOLLOW_RATE: 0.045,
  DRONE_HEIGHT_ABOVE_PLAYER: 105,
  DRONE_BULLET_SPEED: 5.5,
  DRONE_BULLET_LIFE: 100,
  DRONE_SHOT_INTERVAL: 22,
  DRONE_SHOTS: 3,
  DRONE_FIRE_TIME: 45,
  DRONE_BURST_COOLDOWN: 130,
  DRONE_FIRE_MOVE_FACTOR: 0.2,
  DRONE_COUNT: 1,
  EVIL_SPIKE_WARNING_TIME: 30,
  EVIL_SPIKE_DASH_SPEED: 14,
  EVIL_SPIKE_DASH_TIME: 24,
  EVIL_SPIKE_SIZE: 24,
  DRILL_TURN_RATE: 0.14,
  DRILL_DASH_DELAY: 24,
  GREEN_BALL_COUNT: 2,
  GREEN_BALL_BOUNCE: 9,
  GREEN_BALL_SIZE: 30,
  GREEN_BALL_JUMP_INTERVAL: 75,
  GREEN_BALL_JUMP_SPEED: 7,

  RED_TESSERACTS_PER_LEVEL: 8,
  GOLD_TESSERACTS_PER_LEVEL: 8,
  BLESSING_COSTS: { jump: 3, ammo: 3, speed: 3, dash: 4, magnet: 4 },

  START_LEVEL: 0
};
