var CONFIG = {
  TILE: 40, ROWS: 10, PIECE_COLS: 8, CANVAS_W: 800, CANVAS_H: 400,
  MOVE_SPEED: 0.2, JUMP_POWER: 15, GRAVITY: 0.5, MAX_FALL: 16,
  PLAYER_SIZE: 32, PLAYER_RADIUS: 16, LINE_WIDTH: 3, DOT_DISTANCE: 0.55,
  ENEMY_START_DISTANCE: 280, ENEMY_SPAWN_HEIGHT: 100,
  CUOBID_SPEED: 1.05, CUOBID_DISTANCE_SPEED: 0.0025, CUOBID_MAX_SPEED: 3.25,
  CUOBID_GROUP_SIZE: 5, CUOBID_SIZE: 36, CUOBID_SPAWN_SPACING: 135, CUOBID_MERGE_DISTANCE: 72,
  DRONE_FOLLOW_RATE: 0.035, DRONE_FAST_FOLLOW_RATE: 0.075, DRONE_HEIGHT_ABOVE_PLAYER: 105,
  DRONE_BULLET_SPEED: 6.5, DRONE_BULLET_LIFE: 100, DRONE_SHOT_INTERVAL: 7, DRONE_SHOTS: 3,
  DRONE_BURST_COOLDOWN: 55, DRONE_FIRE_MOVE_FACTOR: 0.35,
  EVIL_SPIKE_WARNING_TIME: 35, EVIL_SPIKE_DASH_SPEED: 6, EVIL_SPIKE_DASH_TIME: 42,
  EVIL_SPIKE_SIZE: 36, DRILL_TURN_RATE: 0.14, GREEN_BALL_COUNT: 4,
  GREEN_BALL_SIZE: 30, GREEN_BALL_JUMP_INTERVAL: 90, GREEN_BALL_JUMP_SPEED: 10,
  RED_TESSARACTS_PER_LEVEL: 3, GOLD_TESSARACT_VALUE: 5,
  PISTOL_DAMAGE: 6, AK_DAMAGE: 8, BAZOOKA_DAMAGE: 100, PISTOL_COOLDOWN: 120,
  START_LEVEL: 0
};
