/* =====================================================================
   draw.js -- EVERYTHING YOU CAN SEE.
   ===================================================================== */
var Draw = { canvas: null, ctx: null, cameraX: 0 };
Draw.setup = function () { Draw.canvas = document.getElementById("game"); Draw.ctx = Draw.canvas.getContext("2d"); };
Draw.updateCamera = function () { Draw.cameraX = Player.x - CONFIG.CANVAS_W / 2; if (Draw.cameraX < 0) Draw.cameraX = 0; var furthest = Level.pixelWidth() - CONFIG.CANVAS_W; if (furthest < 0) furthest = 0; if (Draw.cameraX > furthest) Draw.cameraX = furthest; };
Draw.everything = function () { var ctx = Draw.ctx; ctx.fillStyle = "#000000"; ctx.fillRect(0, 0, CONFIG.CANVAS_W, CONFIG.CANVAS_H); ctx.save(); ctx.translate(-Draw.cameraX, 0); Draw.world(); Draw.enemies(); Draw.player(); ctx.restore(); };
Draw.world = function () { var size = CONFIG.TILE, firstCol = Math.floor(Draw.cameraX / size) - 1, lastCol = firstCol + Math.ceil(CONFIG.CANVAS_W / size) + 2; for (var row = 0; row < CONFIG.ROWS; row++) for (var col = firstCol; col <= lastCol; col++) { var here = Level.charAt(col, row), x = col * size, y = row * size; if (here === "#") Draw.block(x, y, size); if (here === "^") Draw.spike(x, y, size); if (here === "F") Draw.finish(x, y, size); } };
Draw.block = function (x, y, size) { var ctx = Draw.ctx; ctx.fillStyle = "#ff0000"; ctx.fillRect(x, y, size, size); ctx.strokeStyle = "#ff0000"; ctx.lineWidth = CONFIG.LINE_WIDTH; ctx.strokeRect(x, y, size, size); };
Draw.spike = function (x, y, size) { var ctx = Draw.ctx; ctx.fillStyle = "#ff0000"; ctx.beginPath(); ctx.moveTo(x, y + size); ctx.lineTo(x + size / 2, y); ctx.lineTo(x + size, y + size); ctx.closePath(); ctx.fill(); };
Draw.finish = function (x, y, size) { var ctx = Draw.ctx; ctx.fillStyle = "#ff0000"; ctx.fillRect(x + size / 2 - 2, y, 4, size); ctx.beginPath(); ctx.moveTo(x + size / 2 + 2, y + 4); ctx.lineTo(x + size - 4, y + 12); ctx.lineTo(x + size / 2 + 2, y + 20); ctx.closePath(); ctx.fill(); };
Draw.enemies = function () { var ctx = Draw.ctx; for (var i = 0; i < Enemy.enemies.length; i++) { var e = Enemy.enemies[i]; if (e.type === "drill" && e.state === "approach") { ctx.save(); ctx.strokeStyle = "#ff3333"; ctx.lineWidth = 2; ctx.setLineDash([8, 6]); ctx.beginPath(); ctx.moveTo(e.x, e.y); ctx.lineTo(Player.x + CONFIG.PLAYER_SIZE / 2, Player.y + CONFIG.PLAYER_SIZE / 2); ctx.stroke(); ctx.restore(); } ctx.save(); ctx.translate(e.x, e.y); ctx.rotate(e.angle || 0); if (e.type === "cuboid") { var r = e.radius; ctx.fillStyle = "#080808"; ctx.fillRect(-r, -r, r * 2, r * 2); ctx.strokeStyle = "#ff2020"; ctx.lineWidth = 3; ctx.strokeRect(-r, -r, r * 2, r * 2); ctx.fillStyle = "#3a0000"; ctx.beginPath(); ctx.moveTo(-r, -r); ctx.lineTo(-r + 10, -r - 10); ctx.lineTo(r + 10, -r - 10); ctx.lineTo(r, -r); ctx.closePath(); ctx.fill(); ctx.fillStyle = "#750000"; ctx.beginPath(); ctx.moveTo(r, -r); ctx.lineTo(r + 10, -r - 10); ctx.lineTo(r + 10, r - 10); ctx.lineTo(r, r); ctx.closePath(); ctx.fill(); } else if (e.type === "drone") { ctx.fillStyle = "#ffaa00"; ctx.fillRect(-20, -12, 40, 24); ctx.fillRect(-28, -18, 56, 5); } else if (e.type === "drill") { ctx.fillStyle = "#ff6600"; ctx.beginPath(); ctx.moveTo(e.radius + 8, 0); ctx.lineTo(-e.radius, -e.radius); ctx.lineTo(-e.radius, e.radius); ctx.closePath(); ctx.fill(); } else { ctx.fillStyle = "#19d34a"; ctx.beginPath(); ctx.arc(0, 0, e.radius, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "#9affad"; ctx.stroke(); } ctx.restore(); } ctx.fillStyle = "#ffff00"; for (var j = 0; j < Enemy.bullets.length; j++) { var b = Enemy.bullets[j]; ctx.beginPath(); ctx.arc(b.x, b.y, 4, 0, Math.PI * 2); ctx.fill(); } };
Draw.player = function () { var ctx = Draw.ctx, r = CONFIG.PLAYER_RADIUS, centerX = Player.x + CONFIG.PLAYER_SIZE / 2, centerY = Player.y + CONFIG.PLAYER_SIZE / 2; ctx.fillStyle = "#000000"; ctx.strokeStyle = "#ff0000"; ctx.lineWidth = CONFIG.LINE_WIDTH; ctx.beginPath(); ctx.arc(centerX, centerY, r, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); var dotX = centerX + Math.cos(Player.angle) * r * CONFIG.DOT_DISTANCE, dotY = centerY + Math.sin(Player.angle) * r * CONFIG.DOT_DISTANCE; ctx.fillStyle = "#ff0000"; ctx.beginPath(); ctx.arc(dotX, dotY, 4, 0, Math.PI * 2); ctx.fill(); };
